// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNC1XdIPHVzXt6GKqcLCFcGICY4oY7Tk',
    appId: '1:449124712115:web:a68adc1b4f3836b12dbac6',
    messagingSenderId: '449124712115',
    projectId: 'cybersec-6966a',
    authDomain: 'cybersec-6966a.firebaseapp.com',
    storageBucket: 'cybersec-6966a.appspot.com',
    measurementId: 'G-9WES4YNW86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9VqdDVn3b5miBv7xR_BUvEG98uPw1BYo',
    appId: '1:449124712115:android:a0579223ec943a0b2dbac6',
    messagingSenderId: '449124712115',
    projectId: 'cybersec-6966a',
    storageBucket: 'cybersec-6966a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFejW-Juhn5I5OqIbcNZ01Z42bAii_F4E',
    appId: '1:449124712115:ios:01fdb7736b341fbc2dbac6',
    messagingSenderId: '449124712115',
    projectId: 'cybersec-6966a',
    storageBucket: 'cybersec-6966a.appspot.com',
    iosBundleId: 'com.example.primeTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFejW-Juhn5I5OqIbcNZ01Z42bAii_F4E',
    appId: '1:449124712115:ios:01fdb7736b341fbc2dbac6',
    messagingSenderId: '449124712115',
    projectId: 'cybersec-6966a',
    storageBucket: 'cybersec-6966a.appspot.com',
    iosBundleId: 'com.example.primeTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMNC1XdIPHVzXt6GKqcLCFcGICY4oY7Tk',
    appId: '1:449124712115:web:87700accf9d8c3b52dbac6',
    messagingSenderId: '449124712115',
    projectId: 'cybersec-6966a',
    authDomain: 'cybersec-6966a.firebaseapp.com',
    storageBucket: 'cybersec-6966a.appspot.com',
    measurementId: 'G-MVTL9VYTRY',
  );
}
